### ISSUE TITLE
Can you provide a BaiduYun link of the pre-trained deeplab-v3 plus model ?

### ISSUE THREAD

**Issue by carrierlxk** [hualin95/Deeplab-v3plus#1]
Thank you very much!

**Comment by hualin95** [comment]
>           Thank you very much!

Yes, https://pan.baidu.com/s/1GwPipBMvlTMdlKd0hZWSWQ is the link you need!

**Comment by hualin95** [comment]
>           Thank you very much!



Yes,  https://pan.baidu.com/s/1cg4_JfBaPxuNtB3tixMsRw is the link you need!

**Comment by carrierlxk** [comment]
Thanks!

**Comment by sm176357** [comment]
Hello, would you mind sharing the pre-trained model on PASCAL VOC 2012 ? The above link seems to have expired.
