### ISSUE TITLE
Fail to produce the 79.19% result.

### ISSUE THREAD

**Issue by gasvn** [hualin95/Deeplab-v3plus#3]
I followed the settings provided by your codes. And the batch size is 16 on 4 GPUs. But my best result is about 74.2%, which is far too low compared to your reported result. 
Can you give me some hits? Thanks.

**Comment by hualin95** [comment]
Have you changed the parameter of [dataset,](https://github.com/hualin95/Deeplab-v3plus/blob/3d12972ba0e04cbdaea8f9afa35064646316847f/tools/train_voc.py#L399)  which I have set as "voc2012" but you should choose "voc2012_aug" if you want to get a result of 79.19%.

**Comment by gasvn** [comment]
> Have you changed the parameter of [dataset,](https://github.com/hualin95/Deeplab-v3plus/blob/3d12972ba0e04cbdaea8f9afa35064646316847f/tools/train_voc.py#L399) which I have set as "voc2012" but you should choose "voc2012_aug" if you want to get a result of 79.19%.

Thanks! I have changed this param to "voc2012_aug", and the training curve shows a stable improvement.

**Comment by zhengxinvip** [comment]
> Have you changed the parameter of dataset, which I have set as "voc2012" but you should choose "voc2012_aug" if you want to get a result of 79.19%.
> 
> Thanks! I have changed this param to "voc2012_aug", and the training curve shows a stable improvement.

How did you train the model ?  I do not find the train.py file in /tools folders. and  when I use python train_voc.py I got this error:
Traceback (most recent call last):
  File "train_voc.py", line 22, in <module>
    from libs.modules.sync_batchnorm.replicate import patch_replication_callback
ModuleNotFoundError: No module named 'libs.modules'
I can not find the libs folder. what is wrong with me? thanks.
