### ISSUE TITLE
ASSP weights and bias did not update

### ISSUE THREAD

**Issue by wyxhahaha** [hualin95/Deeplab-v3plus#5]
Thank you very much for such good source code. I trained it with another dataset for 500epoch, segmentation results seem to be well, but when I check parameters , I found weights  in ASPP convolutions 0.1  1.1   2.1  3. 1   4.1  are all one and bias are all zeros, just equals to parameters after initialization, I wonder is it the same case when you trained on PASCAL VOC datasets? And why comes this case? 
I would really appreciate it if you can help me with some advice.Thanks a lot.

**Comment by hualin95** [comment]
>           Thank you very much for such good source code. I trained it with another dataset for 500epoch, segmentation results seem to be well, but when I check parameters , I found weights  in ASPP convolutions 0.1  1.1   2.1  3. 1   4.1  are all one and bias are all zeros, just equals to parameters after initialization, I wonder is it the same case when you trained on PASCAL VOC datasets? And why comes this case?
> I would really appreciate it if you can help me with some advice.Thanks a lot.

Yes，you are right! I have check the code and have found the problem in https://github.com/hualin95/Deeplab-v3plus/blob/3d12972ba0e04cbdaea8f9afa35064646316847f/tools/train_voc.py#L81 where I have forgot to set learning rate for BN layer. Fixed code will be uploaded soon!
