### ISSUE TITLE
I got a very low MIoU, MPA1 value when I started training. Only 0.03

### ISSUE THREAD

**Issue by kkkmax** [hualin95/Deeplab-v3plus#6]
Hello, I am very grateful to share your results. I have encountered some problems during the training process.

I briefly report my work:
    1) Download data
    2) Modify the loading position of the data
     3) Start training
Training command: $ python train_voc.py --gpu 0

Code section: In addition to modifying the connection location of the data and printing some information about the training process, I have not modified any code.

I see that other people's training initialization MIoU is close to 0.3--0.4, and my initial is only 0.03, and there is no upward trend, I don't understand why?

![los](https://user-images.githubusercontent.com/42377340/51012305-7cd3a180-1597-11e9-930f-794eac328b34.png)

**Comment by hualin95** [comment]
> Hello, I am very grateful to share your results. I have encountered some problems during the training process.
> 
> I briefly report my work:
> 1) Download data
> 2) Modify the loading position of the data
> 3) Start training
> Training command: $ python train_voc.py --gpu 0
> 
> Code section: In addition to modifying the connection location of the data and printing some information about the training process, I have not modified any code.
> 
> I see that other people's training initialization MIoU is close to 0.3--0.4, and my initial is only 0.03, and there is no upward trend, I don't understand why?
> 
> ![los](https://user-images.githubusercontent.com/42377340/51012305-7cd3a180-1597-11e9-930f-794eac328b34.png)

I guess you need increase you GPU nums and batch size.

**Comment by guvcolie** [comment]
@kkkmax hello! I get the same question like you, 1st epoch's mIoU is only 0.03. Do you solve it?
